INSERT INTO PUBLIC.EXPERT (EXPERT_ID, EXPERT_NAME, EXPERT_PASSWORD) VALUES (1, 'dog', 'doge#');
INSERT INTO PUBLIC.EXPERT (EXPERT_ID, EXPERT_NAME, EXPERT_PASSWORD) VALUES (2, 'cat', 'cate');
INSERT INTO PUBLIC.EXPERT (EXPERT_ID, EXPERT_NAME, EXPERT_PASSWORD) VALUES (3, 'chick', 'chicken');

INSERT INTO PUBLIC.MARKET (MARKET_ID, MARKET_NAME, PRINCIPAL) VALUES (1, '开心菜市场', '天哥');
INSERT INTO PUBLIC.MARKET (MARKET_ID, MARKET_NAME, PRINCIPAL) VALUES (2, '关门市场', '地弟');

INSERT INTO PUBLIC.PRODUCT_TYPE (PRODUCT_TYPE_ID, PRODUCT_TYPE_NAME) VALUES (1, '畜禽肉类');
INSERT INTO PUBLIC.PRODUCT_TYPE (PRODUCT_TYPE_ID, PRODUCT_TYPE_NAME) VALUES (2, '蔬菜类');
INSERT INTO PUBLIC.PRODUCT_TYPE (PRODUCT_TYPE_ID, PRODUCT_TYPE_NAME) VALUES (3, '水产品');

INSERT INTO PUBLIC.EXPERT_TASK_GROUP (EXPERT_TASK_GROUP_ID, DEADLINE, TASK_DESCRIPTION) VALUES (1, '2021-01-15', '');
INSERT INTO PUBLIC.EXPERT_TASK (EXPERT_TASK_ID, IS_FINISHED, EXPERT_TASK_GROUP_ID, EXPERT_ID) VALUES (1, false, 1, 1);
INSERT INTO PUBLIC.EXPERT_TASK_ITEM (EXPERT_TASK_ITEM_ID, EXPERT_TASK_ID, PRODUCT_TYPE_ID, UNQUALIFIED_NUMBER, IS_FINISHED, FINISH_DATE) VALUES (1, 1, 1, 10, false, '2021-01-14');

INSERT INTO PUBLIC.MARKET_TASK_GROUP (MARKET_TASK_GROUP_ID, DEADLINE, TASK_DESCRIPTION) VALUES (1, '2021-01-16', null);
INSERT INTO PUBLIC.MARKET_TASK (MARKET_TASK_ID, IS_FINISHED, MARKET_TASK_GROUP_ID, MARKET_ID) VALUES (1, true, 1, 1);
INSERT INTO PUBLIC.MARKET_TASK_ITEM (MARKET_TASK_ITEM_ID, MARKET_TASK_ID, PRODUCT_TYPE_ID, UNQUALIFIED_NUMBER, IS_FINISHED, FINISH_DATE) VALUES (1, 1, 1, 30, false, '2021-01-23');
